### ISSUE TITLE
Alter README.md

### ISSUE THREAD

**Issue by AvidCoder101** [shambashib20/shambashib20#1]
Thanks for getting inspiration from my README. I would just like to make you aware that the typing effect text that you have used has the exact same text from mine. You could change this, or if you wanted me to, I could make a PR changing this for you? Thanks (:

**Comment by shambashib20** [comment]
No! I guess you can check right now that I have updated all the text and also changed it's color! If there's still any discrepancy then I will definitely ask you to help me by raising a pr!

Thanks again for visiting my profile!
